apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-manager-tuning-binding
  namespace: tuning
subjects:
- kind: User
  name: msteggin
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: workload-manager-tuning
  apiGroup: rbac.authorization.k8s.io

